#############################################################################
#
# Project Makefile
#
# (c) Wouter van Ooijen (www.voti.nl) 2016
#
# This file is in the public domain.
# 
#############################################################################

# source files in this project (main.cpp is automatically assumed)
#SOURCES := victim.cpp line.cpp drawable.cpp ball.cpp circle.cpp rectangle.cpp wall.cpp
SOURCES :=

# header files in this project
#HEADERS := victim.hpp line.hpp drawable.hpp ball.hpp circle.hpp rectangle.hpp wall.hpp
HEADERS :=

# other places to look for files for this project
SEARCH  :=

# set BMPTK to the next higher directory and defer to the Makefile.due
BMPTK := $(BMPTK)../
include $(BMPTK)Makefile.due
